<?php
$sessionPath = __DIR__ . '/runtime/sessions';
if (!is_dir($sessionPath)) mkdir($sessionPath, 0700, true);
session_save_path($sessionPath);
session_start();
$isAdmin = !empty($_SESSION['archive_admin']);
$settingsFile = __DIR__ . '/data/site.json';
$siteSettings = file_exists($settingsFile) ? json_decode(file_get_contents($settingsFile), true) : [];
$siteSettings = is_array($siteSettings) ? $siteSettings : [];
$siteInitials = $siteSettings['initials'] ?? 'AR';
$siteLogo = $siteSettings['logo'] ?? '';
$siteName = $siteSettings['name'] ?? 'Fr. Alan Relliquette, MSC';
$siteTagline = $siteSettings['tagline'] ?? 'Texts, language & scholarship';
$color = function($key, $fallback) use ($siteSettings) {
  $value = $siteSettings[$key] ?? $fallback;
  return preg_match('/^#[0-9a-fA-F]{6}$/', $value) ? $value : $fallback;
};
$siteColors = ['ink'=>$color('colorInk','#132722'),'forest'=>$color('colorPrimary','#193d33'),'cream'=>$color('colorSurface','#f4f0e7'),'paper'=>$color('colorBackground','#fbfaf6'),'gold'=>$color('colorAccent','#c5a56a')];
$headingFonts = ['libre-caslon'=>"'Libre Caslon Display', Georgia, serif",'cormorant'=>"'Cormorant Garamond', Georgia, serif",'playfair'=>"'Playfair Display', Georgia, serif",'lora'=>"'Lora', Georgia, serif",'fraunces'=>"'Fraunces', Georgia, serif",'marcellus'=>"'Marcellus', Georgia, serif",'newsreader'=>"'Newsreader', Georgia, serif",'dm-serif'=>"'DM Serif Display', Georgia, serif",'bodoni'=>"'Bodoni Moda', Georgia, serif",'space-grotesk'=>"'Space Grotesk', Arial, sans-serif"];
$bodyFonts = ['dm-sans'=>"'DM Sans', Arial, sans-serif",'inter'=>"'Inter', Arial, sans-serif",'source-sans'=>"'Source Sans 3', Arial, sans-serif",'nunito'=>"'Nunito Sans', Arial, sans-serif",'manrope'=>"'Manrope', Arial, sans-serif",'outfit'=>"'Outfit', Arial, sans-serif",'work-sans'=>"'Work Sans', Arial, sans-serif"];
$siteHeadingFont = $headingFonts[$siteSettings['headingFont'] ?? 'libre-caslon'] ?? $headingFonts['libre-caslon'];
$siteBodyFont = $bodyFonts[$siteSettings['bodyFont'] ?? 'dm-sans'] ?? $bodyFonts['dm-sans'];
$contactParish = $siteSettings['contactParish'] ?? 'Immaculate Concepcion Parish';
$contactAddress = $siteSettings['contactAddress'] ?? 'Villa Kananga, Butuan City';
$contactEmail = $siteSettings['contactEmail'] ?? '';
$contactPhones = $siteSettings['contactPhones'] ?? [
  ['label'=>'TNT','number'=>'0951-880-9712'],
  ['label'=>'SMART','number'=>'0928-870-1387'],
  ['label'=>'GLOBE','number'=>'0966-866-9261']
];
$socialLinks = $siteSettings['socialLinks'] ?? [];
$contentFile = __DIR__ . '/data/content.json';
$items = file_exists($contentFile) ? json_decode(file_get_contents($contentFile), true) : [];
$items = is_array($items) ? $items : [];
usort($items, fn($a, $b) => strcmp($b['date'] ?? '', $a['date'] ?? ''));
$slug = isset($_GET['item']) ? preg_replace('/[^a-z0-9-]/', '', strtolower($_GET['item'])) : '';
$selected = null;
foreach ($items as $item) if (($item['slug'] ?? '') === $slug) $selected = $item;
function e($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function readingTime($text) { return max(1, (int)ceil(str_word_count(strip_tags($text)) / 220)); }
function phoneLink($number) { return 'tel:'.preg_replace('/[^+0-9]/', '', $number); }
function socialIcon($network) {
  $paths = [
    'facebook'=>'<path d="M14 8h3V4h-3c-3.3 0-5 2-5 5v2H6v4h3v9h4v-9h3.5l.5-4h-4V9c0-.7.3-1 1-1z"/>',
    'instagram'=>'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" class="fill"/>',
    'youtube'=>'<path d="M22 12s0-4-1-6c-.6-1-1.5-1.2-2.5-1.4C16.8 4.2 12 4.2 12 4.2s-4.8 0-6.5.4C4.5 4.8 3.6 5 3 6c-1 2-1 6-1 6s0 4 1 6c.6 1 1.5 1.2 2.5 1.4 1.7.4 6.5.4 6.5.4s4.8 0 6.5-.4c1-.2 1.9-.4 2.5-1.4 1-2 1-6 1-6z"/><path d="m10 9 6 3-6 3z" class="cut"/>',
    'x'=>'<path d="M5 4h4.2l3.6 5.1L17.2 4H19l-5.4 6.4L20 20h-4.2l-4.1-5.8L6.8 20H5l5.9-7.1z"/>',
    'tiktok'=>'<path d="M15 3c.4 2.3 1.7 3.7 4 4v3c-1.6 0-2.9-.5-4-1.3V15a6 6 0 1 1-6-6v3a3 3 0 1 0 3 3V3z"/>',
    'linkedin'=>'<path d="M5 8h3v11H5zM6.5 3.5a1.8 1.8 0 1 1 0 3.6 1.8 1.8 0 0 1 0-3.6zM10 8h3v1.5c.8-1.2 2-1.8 3.5-1.8 3 0 3.5 2 3.5 5V19h-3v-5.3c0-1.6-.3-3-2-3s-2 1.4-2 3V19h-3z"/>'
  ];
  return '<svg viewBox="0 0 24 24" aria-hidden="true">'.($paths[$network] ?? '').'</svg>';
}
if ($selected):
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?= e($selected['title']) ?> &middot; <?= e($siteName) ?></title><meta name="description" content="<?= e($selected['excerpt']) ?>">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@400;500;600&family=Cormorant+Garamond:wght@400;500;600&family=DM+Sans:wght@400;500;600&family=DM+Serif+Display&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Inter:wght@400;500;600&family=Libre+Caslon+Display&family=Lora:wght@400;500;600&family=Manrope:wght@400;500;600&family=Marcellus&family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Nunito+Sans:wght@400;500;600&family=Outfit:wght@400;500;600&family=Playfair+Display:wght@400;500;600&family=Source+Sans+3:wght@400;500;600&family=Space+Grotesk:wght@400;500;600&family=Work+Sans:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/site.css"><link rel="stylesheet" href="assets/css/contact.css"><link rel="stylesheet" href="assets/css/audio.css"><link rel="stylesheet" href="assets/css/logo.css"><link rel="stylesheet" href="assets/css/social.css"><style>:root{--ink:<?= e($siteColors['ink']) ?>;--forest:<?= e($siteColors['forest']) ?>;--cream:<?= e($siteColors['cream']) ?>;--paper:<?= e($siteColors['paper']) ?>;--gold:<?= e($siteColors['gold']) ?>;--serif:<?= $siteHeadingFont ?>;--sans:<?= $siteBodyFont ?>}</style></head>
<body><header class="site-header"><a class="brand" href="./"><span><?php if($siteLogo): ?><img src="<?= e($siteLogo) ?>" alt="<?= e($siteName) ?> logo"><?php else: ?><?= e($siteInitials) ?><?php endif; ?></span><strong><?= e($siteName) ?><small><?= e($siteTagline) ?></small></strong></a><button class="menu-button" aria-label="Open menu">Menu</button><nav><a href="./#collection">Collection</a><a href="./#journal">Journal</a><a href="./#about">About</a><a href="./#contact">Contact</a><?php if($isAdmin):?><?php if($isAdmin):?><a class="nav-cta" href="admin.php">Add content</a><?php endif;?><?php endif;?></nav></header>
<main><article class="article"><a class="back" href="./">&larr; Back to the archive</a><div class="article-meta"><span><?= e($selected['category']) ?></span><span><?= e(date('F j, Y', strtotime($selected['date']))) ?></span><span><?= readingTime($selected['body']) ?> min read</span></div><h1><?= e($selected['title']) ?></h1><p class="article-deck"><?= e($selected['excerpt']) ?></p><?php if (!empty($selected['image'])): ?><img class="article-image" src="<?= e($selected['image']) ?>" alt="<?= e($selected['imageAlt'] ?: $selected['title']) ?>"><?php endif; ?><?php if (!empty($selected['audio'])): ?><section class="audio-player"><p>Listen to this entry</p><audio controls preload="metadata" src="<?= e($selected['audio']) ?>">Your browser does not support audio playback.</audio></section><?php endif; ?><div class="article-body"><?= $selected['body'] ?></div></article></main>
<footer><div><strong><?= e($siteName) ?></strong><p><?php if($contactParish):?><?= e($contactParish) ?><br><?php endif;?><?= e($contactAddress) ?></p><?php if($contactEmail):?><a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a><?php endif;?></div><div class="footer-contact"><?php foreach($contactPhones as $phone): if(empty($phone['number'])) continue;?><a href="<?= e(phoneLink($phone['number'])) ?>"><?= e($phone['label'] ?: 'Phone') ?>: <?= e($phone['number']) ?></a><?php endforeach;?></div><?php $footerSocials=array_filter($socialLinks); if($footerSocials):?><div class="footer-social"><?php foreach($footerSocials as $network=>$url):?><a href="<?= e($url) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= e(ucfirst($network)) ?>"><?= socialIcon($network) ?></a><?php endforeach;?></div><?php endif;?><?php if($isAdmin):?><?php if($isAdmin):?><a href="admin.php">Content studio</a><?php endif;?><?php endif;?><span>&copy; <?= date('Y') ?></span></footer><script src="assets/js/site.js"></script></body></html>
<?php exit; endif;
$translations = array_values(array_filter($items, fn($i) => ($i['type'] ?? '') === 'transliteration'));
$articles = array_values(array_filter($items, fn($i) => ($i['type'] ?? '') === 'article'));
$languages = array_filter(array_column($items, 'language'), fn($v) => $v && $v !== 'Editorial');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($siteName) ?> &middot; A Living Archive of Language</title><meta name="description" content="Transliterations, language notes, essays, and source-text studies by <?= e($siteName) ?>."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@400;500;600&family=Cormorant+Garamond:wght@400;500;600&family=DM+Sans:wght@400;500;600&family=DM+Serif+Display&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Inter:wght@400;500;600&family=Libre+Caslon+Display&family=Lora:wght@400;500;600&family=Manrope:wght@400;500;600&family=Marcellus&family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Nunito+Sans:wght@400;500;600&family=Outfit:wght@400;500;600&family=Playfair+Display:wght@400;500;600&family=Source+Sans+3:wght@400;500;600&family=Space+Grotesk:wght@400;500;600&family=Work+Sans:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/site.css"><link rel="stylesheet" href="assets/css/contact.css"><link rel="stylesheet" href="assets/css/audio.css"><link rel="stylesheet" href="assets/css/logo.css"><link rel="stylesheet" href="assets/css/social.css"><style>:root{--ink:<?= e($siteColors['ink']) ?>;--forest:<?= e($siteColors['forest']) ?>;--cream:<?= e($siteColors['cream']) ?>;--paper:<?= e($siteColors['paper']) ?>;--gold:<?= e($siteColors['gold']) ?>;--serif:<?= $siteHeadingFont ?>;--sans:<?= $siteBodyFont ?>}</style></head>
<body><header class="site-header"><a class="brand" href="./"><span><?php if($siteLogo): ?><img src="<?= e($siteLogo) ?>" alt="<?= e($siteName) ?> logo"><?php else: ?><?= e($siteInitials) ?><?php endif; ?></span><strong><?= e($siteName) ?><small><?= e($siteTagline) ?></small></strong></a><button class="menu-button" aria-label="Open menu">Menu</button><nav><a href="#collection">Collection</a><a href="#journal">Journal</a><a href="#about">About</a><a href="#contact">Contact</a><?php if($isAdmin):?><?php if($isAdmin):?><a class="nav-cta" href="admin.php">Add content</a><?php endif;?><?php endif;?></nav></header>
<main><section class="hero"><div class="hero-copy"><p class="kicker">A living archive of language</p><h1>Words carried<br><em>across scripts.</em></h1><p class="hero-lede">Transliterations, language notes, and source-text studies&mdash;carefully preserved and made accessible to new readers.</p><div class="hero-actions"><a class="button button-light" href="#collection">Explore the archive</a><a class="text-link" href="#about">Discover the project <span>&#8599;</span></a></div><div class="hero-stats"><div><b><?= count($translations) ?></b><span>Texts archived</span></div><div><b><?= count(array_unique($languages)) ?></b><span>Languages</span></div><div><b><?= count($articles) ?></b><span>Essays & notes</span></div></div></div><div class="hero-visual"><img src="assets/images/archive-study.jpg" alt="An archival manuscript on a wooden reading stand"><p><span>Featured archive</span>Preserving written traditions, one text at a time.</p></div></section>
<section class="intro" id="about"><p class="kicker">The work</p><div><h2>Reading the past.<br>Sharing it forward.</h2><p>Transliteration opens a path between writing systems while preserving the structure and character of the source. This archive brings together texts, commentary, and the context that gives each work meaning.</p></div></section>
<section class="collection" id="collection"><div class="section-title"><div><p class="kicker">Featured collection</p><h2>From the archive</h2></div><div class="filters"><button class="active" data-filter="all">All</button><button data-filter="transliteration">Transliterations</button><button data-filter="article">Essays</button></div></div><div class="card-grid">
<?php foreach ($items as $index => $item): ?><article class="archive-card <?= $index === 0 ? 'card-wide' : '' ?>" data-type="<?= e($item['type']) ?>"><a class="card-image" href="?item=<?= e($item['slug']) ?>"><img src="<?= e($item['image'] ?: 'assets/images/archive-study.jpg') ?>" alt="<?= e($item['imageAlt'] ?: $item['title']) ?>"><span><?= e($item['category']) ?></span></a><div class="card-content"><div class="card-meta"><?= e($item['language'] ?: 'Editorial') ?> &middot; <?= e(date('Y', strtotime($item['date']))) ?><?php if(!empty($item['audio'])): ?> &middot; Audio<?php endif; ?></div><h3><a href="?item=<?= e($item['slug']) ?>"><?= e($item['title']) ?></a></h3><p><?= e($item['excerpt']) ?></p><a class="read" href="?item=<?= e($item['slug']) ?>">Read <?= $item['type'] === 'article' ? 'essay' : 'text' ?> <span>&rarr;</span></a></div></article><?php endforeach; ?>
<?php if (!$items): ?><div class="empty"><h3>Your archive is ready.</h3><p>Add the first story, text, or image from the content studio.</p><?php if($isAdmin):?><a class="button" href="admin.php">Add content</a><?php endif;?></div><?php endif; ?></div></section>
<section class="quote"><span>&ldquo;</span><blockquote>Every script carries more than words&mdash;it carries a way of seeing, remembering, and belonging.</blockquote><p>On the purpose of this archive</p></section>
<section class="contact" id="contact"><div><p class="kicker">Get in touch</p><?php if($contactParish):?><h2><?= e($contactParish) ?></h2><?php endif;?><?php if($contactAddress):?><p><?= e($contactAddress) ?></p><?php endif;?><?php if($contactEmail):?><a class="contact-email" href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a><?php endif;?><?php $activeSocials=array_filter($socialLinks); if($activeSocials):?><div class="social-links"><?php foreach($activeSocials as $network=>$url):?><a href="<?= e($url) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= e(ucfirst($network)) ?>"><?= socialIcon($network) ?></a><?php endforeach;?></div><?php endif;?></div><div class="contact-numbers"><?php foreach($contactPhones as $phone): if(empty($phone['number'])) continue;?><a href="<?= e(phoneLink($phone['number'])) ?>"><span><?= e($phone['label'] ?: 'Phone') ?></span><?= e($phone['number']) ?></a><?php endforeach;?></div></section><section class="journal" id="journal"><div class="section-title"><div><p class="kicker">Notes & essays</p><h2>From the journal</h2></div></div><div class="journal-list"><?php foreach (array_slice($articles, 0, 4) as $item): ?><a href="?item=<?= e($item['slug']) ?>"><time><?= e(date('M d', strtotime($item['date']))) ?><small><?= e(date('Y', strtotime($item['date']))) ?></small></time><div><span><?= e($item['category']) ?></span><h3><?= e($item['title']) ?></h3><p><?= e($item['excerpt']) ?></p></div><b>&#8599;</b></a><?php endforeach; ?></div></section></main>
<footer><div><strong><?= e($siteName) ?></strong><p><?php if($contactParish):?><?= e($contactParish) ?><br><?php endif;?><?= e($contactAddress) ?></p><?php if($contactEmail):?><a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a><?php endif;?></div><div class="footer-contact"><?php foreach($contactPhones as $phone): if(empty($phone['number'])) continue;?><a href="<?= e(phoneLink($phone['number'])) ?>"><?= e($phone['label'] ?: 'Phone') ?>: <?= e($phone['number']) ?></a><?php endforeach;?></div><?php $footerSocials=array_filter($socialLinks); if($footerSocials):?><div class="footer-social"><?php foreach($footerSocials as $network=>$url):?><a href="<?= e($url) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= e(ucfirst($network)) ?>"><?= socialIcon($network) ?></a><?php endforeach;?></div><?php endif;?><?php if($isAdmin):?><?php if($isAdmin):?><a href="admin.php">Content studio</a><?php endif;?><?php endif;?><span>&copy; <?= date('Y') ?></span></footer><script src="assets/js/site.js"></script></body></html>

