<?php
$sessionPath=__DIR__.'/runtime/sessions';
if(!is_dir($sessionPath)) mkdir($sessionPath,0700,true);
session_save_path($sessionPath);
ini_set('session.use_strict_mode','1');
session_set_cookie_params(['httponly'=>true,'samesite'=>'Lax','secure'=>(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')]);
session_start();
if(empty($_SESSION['archive_admin'])){header('Location: admin.php');exit;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Visual Manual · Content Studio</title><link rel="stylesheet" href="assets/css/admin.css"><link rel="stylesheet" href="assets/css/admin-modern.css"><link rel="stylesheet" href="assets/css/manual.css"></head>
<body><header><a class="studio-brand" href="./"><span>AR</span><b>Content Studio<small>Visual manual</small></b></a><nav><a href="admin.php">Content archive</a><a href="content-types.php">Content types</a><a href="site-settings.php">Site identity</a><a href="contact-settings.php">Contact & socials</a><a href="admin.php?logout=1">Sign out</a></nav></header>
<main class="manual"><section class="manual-hero"><div><p class="eyebrow">Simple guide</p><h1>Manage the archive with confidence.</h1><p>Follow the numbered path in each visual. Changes are live as soon as you save them.</p></div><button type="button" onclick="window.print()">Print this manual</button></section>
<nav class="task-index" aria-label="Manual sections"><a href="#login">01 Login</a><a href="#types">02 Types</a><a href="#publish">03 Publish</a><a href="#edit">04 Edit</a><a href="#identity">05 Identity</a><a href="#contact">06 Contact</a></nav>

<section class="task" id="login"><div class="task-copy"><span>01</span><p class="eyebrow">Access</p><h2>Sign in securely</h2><ol><li>Open <b>/admin.php</b>.</li><li>Enter the username and password from <b>.env</b>.</li><li>Select <b>Sign in</b>.</li></ol><aside>Use the HTTPS domain, especially when entering a password.</aside></div><div class="mock"><div class="mock-bar"><i></i><i></i><i></i><small>alanrelliquette.online/admin.php</small></div><div class="mock-login"><b>Sign in to your archive.</b><label>Username<span>••••••••</span></label><label>Password<span>••••••••••••</span></label><em>Sign in</em></div></div></section>

<section class="task" id="types"><div class="task-copy"><span>02</span><p class="eyebrow">Organization</p><h2>Add a content type</h2><ol><li>Open <b>Content types</b>.</li><li>Enter a name such as “Homily.”</li><li>Select <b>Add content type</b>.</li></ol><aside>A type cannot be removed while an entry is using it.</aside></div><div class="mock"><div class="mock-bar"><i></i><i></i><i></i><small>Content types</small></div><div class="mock-types"><div><b>Transliteration</b><small>Default</small></div><div><b>Article / essay</b><small>Default</small></div><label>Content type name<span>Homily</span></label><em>Add content type</em></div></div></section>

<section class="task" id="publish"><div class="task-copy"><span>03</span><p class="eyebrow">Main task</p><h2>Publish new content</h2><ol><li>Open <b>Content archive</b> and select <b>New entry</b>.</li><li>Choose the type and publication date.</li><li>Add title, introduction, category, language, and body.</li><li>Upload a cover, optional audio, and picture description.</li><li>Select <b>Publish content</b>.</li></ol><aside>Picture descriptions help visitors who use screen readers.</aside></div><div class="mock"><div class="mock-bar"><i></i><i></i><i></i><small>New entry</small></div><div class="mock-form"><label>Content type<span>Transliteration⌄</span></label><label>Title<span>A clear, descriptive title</span></label><label>Short introduction<span>Summary shown on archive cards</span></label><div class="upload">＋ Cover picture</div><label>Content<span class="area">Begin the text here…</span></label><em>Publish content</em></div></div></section>

<section class="task" id="edit"><div class="task-copy"><span>04</span><p class="eyebrow">Maintenance</p><h2>Edit or delete an entry</h2><ol><li>Select an entry from the archive list.</li><li>Change any field and select <b>Publish content</b>.</li><li>To remove it, select <b>Delete</b> and confirm.</li></ol><aside>Deletion is permanent. Keep a backup of data and uploads.</aside></div><div class="mock"><div class="mock-bar"><i></i><i></i><i></i><small>Editing entry</small></div><div class="mock-edit"><div class="mini-list"><b>Your content</b><span class="selected">Selected entry</span><span>Another entry</span></div><div><b>Update your content</b><span class="save">Publish content</span><span class="danger">Delete</span></div></div></div></section>

<section class="task" id="identity"><div class="task-copy"><span>05</span><p class="eyebrow">Appearance</p><h2>Change identity and theme</h2><ol><li>Open <b>Site identity</b>.</li><li>Upload a square icon if needed.</li><li>Update the display name or tagline.</li><li>Choose a complete theme and save.</li></ol><aside>The preview updates before you save.</aside></div><div class="mock"><div class="mock-bar"><i></i><i></i><i></i><small>Site identity</small></div><div class="mock-identity"><div class="identity-chip"><i>AR</i><b>Fr. Alan Relliquette<small>Texts, language & scholarship</small></b></div><div class="themes"><span class="chosen"></span><span></span><span></span><span></span></div><em>Apply selected theme & save</em></div></div></section>

<section class="task" id="contact"><div class="task-copy"><span>06</span><p class="eyebrow">Public details</p><h2>Update contact information</h2><ol><li>Open <b>Contact & socials</b>.</li><li>Update the organization, address, email, and phone numbers.</li><li>Paste complete social-profile links.</li><li>Select <b>Save contact details</b>.</li></ol><aside>Leave an optional field empty to hide it publicly.</aside></div><div class="mock"><div class="mock-bar"><i></i><i></i><i></i><small>Contact & socials</small></div><div class="mock-form"><label>Parish / organization<span>Organization name</span></label><label>Email address<span>name@example.com</span></label><label>Phone number<span>0951-000-0000</span></label><label>Facebook <small>Optional</small><span>https://facebook.com/…</span></label><em>Save contact details</em></div></div></section>

<section class="quick-rules"><p class="eyebrow">Remember</p><div><article><b>Use HTTPS</b><p>Always manage content through alanrelliquette.online.</p></article><article><b>Write useful alt text</b><p>Describe the picture’s meaning, not only its filename.</p></article><article><b>Back up regularly</b><p>Preserve the data folder and uploads folder together.</p></article></div></section></main></body></html>

